version: "3.8"
services:
  app:
    image: app
    build: .
    depends_on: 
      - rabbitmq
      - mongodb
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports: 
      - 5672:5672 # default
      - 15672:15672 # cli default
  mongodb:
    image: mongo
    ports:
      - 27017:27017 # default
  mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081 # default
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb